# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Alex\YandexDisk\projects\py\misc\edu\crypt\ui\helpdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(905, 416)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RefBrowser = QtWidgets.QTextBrowser(Dialog)
        self.RefBrowser.setObjectName("RefBrowser")
        self.verticalLayout.addWidget(self.RefBrowser)
        self.ButtonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.ButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.ButtonBox.setObjectName("ButtonBox")
        self.verticalLayout.addWidget(self.ButtonBox)

        self.retranslateUi(Dialog)
        self.ButtonBox.accepted.connect(Dialog.accept) # type: ignore
        self.ButtonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Справка"))
